version: '3.1'

services:
  web:
    build:
      context: ./web/
      network: host
    ports:
      - '3000:3000'
  api:
    build:
      context: ./api/
      network: host
    ports:
      - '8080:8080'
